### ISSUE TITLE
Do you have a walkthrough or step-by-step instruction?

### ISSUE THREAD

**Issue by ralphjsmit** [daviddarnes/netlify-plugin-ghost-markdown#15]
Hey David,

I just stumbled across your plugin and I'd like to use it in order to (every now and then) backup my Ghost installation including the images. 

I've never used Netlify before, neither their build plugins. I've tried some things but I don't really understand what step I'll need to take in order to run your plugin.

Just to be clear: I want get an empty Git repo and periodically or manually, use your plugin to retrieve posts/pages + images inside that repo.

Could you share some walkthrough or step by step instructions about using your plugin?

Many thanks from a beginner!

Ralph

**Comment by daviddarnes** [comment]
Hey @ralphjsmit, I'd say the best and quickest thing you can do is fork this demo repo and update the credentials to your own Ghost installation: https://github.com/daviddarnes/netlify-plugin-ghost-markdown-demo
Here's what I'd do:
1. Fork the repo and set it to private
2. Update the `netlify.toml` file with your own Ghost Content API details
3. Set up a site on Netlify and use your private repo as the source
4. Set up a Build Hook using this guide so when you update content the Netlify backup gets updated https://ghost.org/integrations/netlify/

I think that's everything. By using this setup you're essentially creating an entire static clone of your website, meaning it'll be there forever. Plus with Netlify it'll store all your revisions, so you can travel back in time and get your content back. Because you're making a clone you may want to make it unlisted or password protected so it doesn't affect your live site's SEO

Hope this helps!

**Comment by ralphjsmit** [comment]
Hey David, thanks a lot for your very fast response!

I'm certainly going to try this, thanks!

**Comment by ralphjsmit** [comment]
I got everything working, thanks!

Is there also a way to get the Netlify build files back in e.g. a Git repo? So that I can download it and extract the folder you want?

Perhaps there is something like an option to sync the latest deploy to a specific repo?

**Comment by daviddarnes** [comment]
Netlify can’t really write back to the repo, however if you go to the deploy logs view you can download the whole site from there

**Comment by ralphjsmit** [comment]
Thank you David, I totally missed that button!
