### ISSUE TITLE
How to use when each post folder contains all its images

### ISSUE THREAD

**Issue by aayushdutt** [daviddarnes/netlify-plugin-ghost-markdown#6]
Thanks for the awesome plugin! This is very promising, we get the best of both worlds, owning the content in GitHub markdown files and also being able to add/edit from Ghost's UI.

However, I am having a bit of trouble using this with my current gatsby website.

This is the directory structure of the content folder:
![image](https://user-images.githubusercontent.com/25280541/83223595-d3e01380-a198-11ea-8a44-67ef63f59ab3.png)

How do you think should I approach this?

**Comment by daviddarnes** [comment]
Hey no problem @aayushdutt! The structure in your screenshot seems very elaborate, are you not able to adjust Gatsby to work with the directory structure the plugin supplies? Currently the plugin doesn't handle authors, mainly because there's not really a standard amongst SSGs. However it could be added as a basic key value in the front matter?

I would suggest making the right adjustments to your Gatsby setup so pages, posts and images can reside in their own directories, rather than images being relative to the post.

Hope this helps!
